- name: Run all ansible scripts
  hosts: localhost
  vars:
    source_key: "./.ssh/github_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/github_rsa"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: false
      state: present
    tags:
      - install
      - update
      - setup
  tasks:
    - include: tasks/basic.yml
      tags:
        - setup
    - include: tasks/productivity.yml
      tags: 
        - setup
        - dotfiles
    - include: tasks/git-setup.yml
      tags:
        - setup
    - include: tasks/ssh.yml
      tags:
        - ssh
        - git
    - include: tasks/deno.yml
      tags:
        - deno
        - ts
        - js
    - include: tasks/disconnected.yml
      tags: 
        - setup
    - include: tasks/brave.yml
      tags: 
        - setup
    - include: tasks/dotfiles.yml
      tags:
        - setup
        - dotfiles
    - include: tasks/zettelkasten.yml
      tags:
        - notes
