- name: Run all ansible scripts
  hosts: localhost
  gather_facts: true
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
  pre_tasks:
  - name: Detect if I am on a mac
    stat:
      path: /usr/local/Homebrew/bin/brew
    tags:
      - os
    register: is_brew_installed
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: false
      state: present
    tags:
      - install
      - update
      - setup
    when: ansible_system == "Linux" and ansible_pkg_mgr == "apt"
  tasks:
    - name: Install Packages
      ansible.builtin.include_tasks:
        file:  tasks/packages.yml
    - name: Install Rust
      ansible.builtin.include_tasks:
        file:  tasks/rust.yml
    - name: Setup git
      ansible.builtin.include_tasks:
        file:  tasks/git-setup.yml
    - name: Setup ssh?
      ansible.builtin.include_tasks:
        file:  tasks/ssh.yml
    - name: Setup zettelkasten
      ansible.builtin.include_tasks:
        file:  tasks/zettelkasten.yml
    - name: Setup dotfiles
      ansible.builtin.include_tasks:
        file:  tasks/dotfiles.yml
    - name: Install Neovim
      ansible.builtin.include_tasks: 
        file: tasks/nvim.yml
        apply:
          tags:
            - neovim
            - nvim
    - name: Install Deno
      ansible.builtin.include_tasks:
        file:  tasks/deno.yml
    - name: Install Disconnected
      ansible.builtin.include_tasks:
        file:  tasks/disconnected.yml
    - name: Test
      ansible.builtin.include_tasks:
        file:  tasks/brave.yml
    - name: Test
      ansible.builtin.include_tasks:
        file:  tasks/tmux.yml
    - name: Test
      ansible.builtin.include_tasks:
        file:  tasks/node.yml
