- name: Run all ansible scripts
  hosts: localhost
  gather_facts: true
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
  pre_tasks:
  - name: Detect if I am on a mac
    stat:
      path: /usr/local/Homebrew/bin/brew
    tags:
      - os
      - packages
    register: is_brew_installed
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: false
      state: present
    tags:
      - install
      - update
      - setup
      - packages
    when: ansible_system == "Linux" and ansible_pkg_mgr == "apt"
  tasks:
    - name: Install Packages
      ansible.builtin.include_tasks:
        file:  tasks/packages.yml
      tags: packages

    - name: Install Rust
      ansible.builtin.include_tasks:
        file:  tasks/rust.yml

    - name: Setup git
      ansible.builtin.include_tasks:
        file:  tasks/git-setup.yml

    - name: Setup git ssh and openssh server
      ansible.builtin.include_tasks:
        file:  tasks/ssh.yml
      tags: ssh

    - name: Setup zettelkasten
      ansible.builtin.include_tasks:
        file:  tasks/zettelkasten.yml
      tags: zettelkasten

    - name: Setup dotfiles
      ansible.builtin.include_tasks:
        file:  tasks/dotfiles.yml
      tags: dotfiles

    - name: Install Neovim
      ansible.builtin.include_tasks: 
        file: tasks/nvim.yml
      tags:
        - neovim
        - nvim

    - name: Install Deno
      ansible.builtin.include_tasks:
        file:  tasks/deno.yml

    - name: Install Disconnected
      ansible.builtin.include_tasks:
        file:  tasks/disconnected.yml

    - name: Install Brave
      ansible.builtin.include_tasks:
        file:  tasks/brave.yml

    - name: Install Tmux and set up TPM
      ansible.builtin.include_tasks:
        file:  tasks/tmux.yml

    - name: Install Node
      ansible.builtin.include_tasks:
        file:  tasks/node.yml

    # - name: Install Logseq
    #   ansible.builtin.include_tasks: 
    #     file: tasks/logseq.yml

    - name: Install Leftwm
      ansible.builtin.include_tasks: 
        file: tasks/leftwm.yml
      tags: leftwm

    - name: Install Yazi
      ansible.builtin.include_tasks:
        file:  tasks/yazi.yml
      tags: yazi

    - name: Install Sql Server with Podman
      ansible.builtin.include_tasks:
        file:  tasks/sqlServer.yml
      tags: 
        - never
        - sqlserver

    - name: Install QMK
      ansible.builtin.include_tasks:
        file:  tasks/qmk.yml
      tags: 
        - never
        - qmk
      
    # - name: Install Awesome
    #   ansible.builtin.include_tasks: 
    #     file: tasks/awesome.yml
    #   tags: awesome
