- name: Run all ansible scripts
  hosts: localhost
  gather_facts: true
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
  pre_tasks:
  - name: Detect if I am on a mac
    stat:
      path: /usr/local/Homebrew/bin/brew
    tags:
      - os
    register: is_brew_installed
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: false
      state: present
    tags:
      - install
      - update
      - setup
    when: ansible_system == "Linux" and ansible_pkg_mgr == "apt"
  tasks:
    - include: tasks/packages.yml
      tags: 
        - setup
        - dotfiles
    - include: tasks/rust.yml
      tags:
        - rust
    - include: tasks/git-setup.yml
      tags:
        - setup
    - include: tasks/ssh.yml
      tags:
        - ssh
        - git
    - include: tasks/zettelkasten.yml
      tags:
        - notes
        - zk
    - include: tasks/dotfiles.yml
      tags:
        - setup
        - dotfiles
    - include: tasks/nvim.yml
      tags:
        - neovim
        - nvim
    - include: tasks/deno.yml
      tags:
        - deno
        - ts
        - js
    - include: tasks/disconnected.yml
      tags: 
        - setup
        - dsc
      when: ansible_system == "Linux" or ansible_sytem == "Darwin"
    - include: tasks/brave.yml
      tags: 
        - setup
    - include: tasks/tmux.yml
      tags:
        - tmux
    - include: tasks/node.yml
      tags:
        - node
    - name: Print OS
      tags:
        - os
      debug:
        msg: "The OS is {{ ansible_facts['distribution'] }}"
    - name: Test Ubuntu
      tags:
        - os
      debug:
        msg: "This should print on ubuntu, and nowhere else"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Package Manager
      tags:
        - os
      debug:
        msg: "Package Manager {{ ansible_pkg_mgr }} - {{ 'brew installed' if is_brew_installed.stat.exists else 'brew not installed' }} - {{ ansible_system }}"
