- hosts: localhost
  vars:
    source_key: "./.ssh/github_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/github_rsa"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/basic.yml
    - include: tasks/deno.yml
    - include: tasks/disconnected.yml
    - include: tasks/brave.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zettelkasten.yml
    - include: tasks/productivity.yml
    - include: tasks/git-setup.yml
