- name: Basic setup for computer
  hosts: localhost

  tasks:
    - name: Create Software folder
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Software"
        state: directory
        mode: '0755'
    - name: Create Software Tools folder
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Software/tools"
        state: directory
        mode: '0755'
    - name: Create Software Web folder
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Software/web"
        state: directory
        mode: '0755'
    - name: Create Software Test folder
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Software/test"
        state: directory
        mode: '0755'
