- name: Check if Brave is installed
  ansible.builtin.shell: command -v brave-browser
  register: brave_exists
  changed_when: false
  failed_when: false
  tags: brave

- name: Install Brave dependencies
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - apt-transport-https
    state: present
  when: brave_exists.rc != 0
  tags: brave

- name: Install Brave browser
  become: true
  ansible.builtin.shell: curl -fsS https://dl.brave.com/install.sh | sh
  when: brave_exists.rc != 0
  tags: brave
