- name: Ensure Downloads folder exists
  ansible.builtin.file:
    path: "{{ home_dir }}/Downloads"
    state: directory
    mode: "0755"
  tags: deno

- name: Download Deno installer
  ansible.builtin.get_url:
    url: https://deno.land/x/install/install.sh
    dest: "{{ home_dir }}/Downloads/install-deno.sh"
    mode: "0755"
  tags: deno

- name: Install Deno
  ansible.builtin.command: "{{ home_dir }}/Downloads/install-deno.sh"
  args:
    creates: "{{ home_dir }}/.deno/bin/deno"
  tags: deno

- name: Clean up Deno installer
  ansible.builtin.file:
    path: "{{ home_dir }}/Downloads/install-deno.sh"
    state: absent
  tags: deno
