- name: Check if Downloads folder exists
  stat:
    path: "{{ home_dir }}/Downloads"
  register: downloads_folder

- name: Create Downloads folder if it doesn't exist
  file:
    path: "{{ home_dir }}/Downloads"
    state: directory
  when: not downloads_folder.stat.exists

- name: Download Deno binary
  get_url:
    url: https://deno.land/x/install/install.sh
    dest: "{{ home_dir }}/Downloads/install-deno.sh"
    mode: '+x'  # Make the script executable

- name: Run Deno installer script for user Austin
  command: "{{ home_dir }}/Downloads/install-deno.sh"
  args:
    creates: "{{ home_dir }}/.deno/bin/deno"
