- name: Remove Disconnected
  shell: rm -rf "{{ home_dir }}/disconnected"

- name: Pull Disconnected
  ansible.builtin.git:
    repo: 'git@github.com:austinwilcox/disconnected.git'
    dest: "{{ home_dir }}/disconnected"
    version: master

- name: Compile and deploy command
  shell: "cd {{ home_dir }}/disconnected && {{ home_dir }}/.deno/bin/deno compile --allow-read --allow-env --allow-write --allow-run --output disconnected index.ts"

- name: Move disconnected to /usr/local/bin
  become: yes
  shell: "cd {{ home_dir }}/disconnected && cp disconnected /usr/local/bin"
