- name: Remove Disconnected
  shell: rm -rf "{{ lookup('env', 'HOME') }}/Software/tools/disconnected"

- name: Pull Disconnected
  ansible.builtin.git:
    repo: 'git@github.com:austinwilcox/disconnected.git'
    dest: "{{ lookup('env', 'HOME') }}/Software/tools/disconnected"
    version: master

- name: Compile and deploy command
  shell: "cd {{ lookup('env', 'HOME') }}/Software/tools/disconnected && {{ lookup('env', 'HOME') }}/.deno/bin/deno compile --allow-read --allow-env --allow-write --allow-run --output disconnected index.ts"

- name: Move disconnected to /usr/local/bin
  # become: yes
  shell: "cd {{ lookup('env', 'HOME') }}/Software/tools/disconnected && cp disconnected /usr/local/bin"
