- name: Do dotfiles already exist
  stat:
    path: "{{ lookup('env', 'HOME') }/.dotfiles}"
  register: dotfiles

- name: Print message to alert that dotfiles DO NOT exist
  debug:
    msg: ".Dotfiles not found, pulling from github"
  when: not dotfiles.stat.exists

- name: Print message to alert that dotfiles DO exist
  debug:
    msg: ".Dotfiles found, Should I delete the existing ones or not?"
  when: dotfiles.stat.exists and dotfiles.stat.isdir

- name: If dotfiles do not exist
  when: not dotfiles.stat.exists
  ansible.builtin.git:
    repo: 'git@github.com:austinwilcox/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: master
  

