- name: Do dotfiles already exist
  stat:
    path: "{{ home_dir }}/.dotfiles"
  register: dotfiles

- name: Clone dotfiles if they DO NOT exist
  ansible.builtin.git:
    repo: 'git@github.com:austinwilcox/dotfiles.git'
    dest: "{{ home_dir }}/.dotfiles"
    version: master
  when: not dotfiles.stat.exists

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && stow .
  tags:
    - dotfiles
    - stow

- name: Install eza
  shell: cargo install eza
  ignore_errors: yes
  tags: 
    - ls
    - eza

- name: Install alacritty
  shell: cargo install alacritty
  ignore_errors: yes
