- name: Do dotfiles already exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
  register: dotfiles

- name: Does bashrc exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
  register: bashrc

- name: Does .tmux.conf exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.tmux.conf"
  register: tmuxConf

- name: Does compton.conf exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/compton.conf"
  register: comptonConf

- name: Does nvim conf exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
  register: nvimConf

- name: Does init.lua for nvim exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/init.lua"
  register: initLua

- name: Print message to alert that dotfiles DO NOT exist
  debug:
    msg: "dotfiles not found, at {{ lookup('env', 'HOME') }}/.dotfiles pulling from github"
  when: not dotfiles.stat.exists

- name: Print message to alert that dotfiles DO exist
  debug:
    msg: ".Dotfiles found, Should I delete the existing ones or not?"
  when: dotfiles.stat.exists and dotfiles.stat.isdir

- name: If dotfiles DO NOT exist
  ansible.builtin.git:
    repo: 'git@github.com:austinwilcox/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: master
  when: not dotfiles.stat.exists
  
- name: Create .bashrc symlink
  file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/.bashrc"
    dest: "{{ lookup('env', 'HOME') }}"
    state: link
  when: not bashrc.stat.exists

- name: Create .tmux.conf symlink
  file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/.tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}"
    state: link
  when: not tmuxConf.stat.exists

- name: Create compton.conf symlink
  file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/compton.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config"
    state: link
  when: not comptonConf.stat.exists

- name: Create nvim symlink
  file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/luaConfig/lua"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/"
    state: link
  when: not nvimConf.stat.exists

- name: Create inti.lua symlink
  file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/luaConfig/init.lua"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/"
    state: link
  when: not initLua.stat.exists
