- name: Do dotfiles already exist
  stat:
    path: "{{ home_dir }}/.dotfiles"
  register: dotfiles
- name: Does a bashrc already exist
  stat:
    path: "{{ home_dir }}/.bashrc"
  register: bashrc

- name: Clone dotfiles if they DO NOT exist
  ansible.builtin.git:
    repo: 'git@github.com:austinwilcox/dotfiles.git'
    dest: "{{ home_dir }}/.dotfiles"
    version: master
  when: not dotfiles.stat.exists

- name: Remove bashrc if it exists
  shell: rm ~/.bashrc
  when: bashrc.stat.exists

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && stow .
  tags:
    - dotfiles
    - stow

#This might not be needed, need to test though
- name: Stow Obsidian Vimrc 
  shell: cd $HOME/.dotfiles && stow Zettelkasten-V2 -t ~/Zettelkasten-V2
  tags:
    - zettelkasten
    - zk

- name: Install eza
  shell: cargo install eza
  ignore_errors: yes
  tags: 
    - ls
    - eza

# - name: Install alacritty
#   shell: cargo install alacritty
#   ignore_errors: yes
- name: Download Alacritty
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty.git'
    dest: "{{ home_dir }}/alacritty"
    version: master
  ignore_errors: yes

- name: Build Alacritty
  shell: cd "{{ home_dir }}"/alacritty && cargo build --release && sudo cp target/release/alacritty /usr/local/bin && sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg && sudo desktop-file-install extra/linux/Alacritty.desktop && sudo update-desktop-database
  ignore_errors: yes
  
# Does not work this way because of a prompt to ask for a y from stdin
# - name: Install Starship
#   shell: curl -sS https://starship.rs/install.sh | sh
#   ignore_errors: yes

#TODO: Need to fix this up still
# - name: Install Starship
#   ansible.builtin.expect:
#     command: curl -sS https://starship.rs/install.sh | sh
#     responses:
#       Question:
#       ".*": "y"
#   ignore_errors: yes

# - name: Install Starship
#   shell: curl -sS https://starship.rs/install.sh | sh
#   ignore_errors: yes

- name: Download Nerdfonts
  ansible.builtin.git:
    repo: 'https://github.com/ryanoasis/nerd-fonts.git'
    depth: 1
    dest: "{{ home_dir }}/nerd-fonts"
    version: master

- name: Install UbuntuMono
  shell: cd "{{ home_dir }}"/nerd-fonts && ./install.sh UbuntuMono

  # Run a check if grep -Fxq "kmonad" /etc/crontab is found, which this will return 0 if found, and 1 if not

- name: Check if kmonad is in my crontab
  shell: grep "kmonad" /etc/crontab
  ignore_errors: yes
  register: kmonad_grep

- name: Add kmonad to crontab
  become: true
  shell: echo "@reboot root /home/austin/kmonad/kmonad /home/austin/kmonad/kmonad-layouts/colemak-dh-extend-ansi.kbd" >> /etc/crontab
  when: kmonad_grep is not failed
