- name: Set git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  tags: git

- name: Set git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  tags: git
