- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "me@theaustinwilcox.com"
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Austin Wilcox"
