- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ home_dir }}/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ home_dir }}/neovim && make -j 20"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ home_dir }}/neovim && make install"
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 1
  become: true
  apt: name=luarocks
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim
