# - name: Update packages
#   apt:
#     upgrade: 'yes'

- name: Install packages on Linux
  become: true 
  apt:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "build-essential" ]
    state: latest
  when: ansible_pkg_mgr == "apt"

- name: Install Packages on Darwin
  become: true
  homebrew:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip" ]
    state: latest
  when: is_mac.stat.exists

# TODO: Provide install instructions for alacritty
