- name: Install Homebrew
  become: yes
  command: "/bin/bash -c '{{ url }}'"
  vars:
    url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
  when: ansible_system == "Darwin"

- name: Install packages on Linux
  become: true 
  apt:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "build-essential" ]
    state: latest
  when: ansible_system == "Linux" and ansible_pkg_mgr == "apt"

- name: Install Packages on Darwin
  become: true
  homebrew:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "brave" ]
    state: latest
  when: is_brew_installed.stat.exists

- name: Install Packages on Windows
  win_chocolatey:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "brave" ]
    state: latest
  when: ansible_system == "Windows"

# TODO: Provide install instructions for alacritty
