- name: Install Homebrew
  become: yes
  command: "/bin/bash -c '{{ url }}'"
  vars:
    url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
  when: ansible_system == "Darwin"
  tags: packages

- name: Install packages on Linux
  become: true 
  apt:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "build-essential", "make", "ssh", "cmake", "neofetch", "libfreetype6-dev", "libfontconfig1-dev", "libxcb-xfixes0-dev", "libxkbcommon-dev", "python3", "openssh-server", "thunar", "pavucontrol", "virt-manager", "libreoffice" ]
    state: latest
  when: ansible_system == "Linux" and ansible_pkg_mgr == "apt"
  tags: packages

- name: Install Packages on Darwin
  become: true
  homebrew:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "brave" ]
    state: latest
  when: is_brew_installed.stat.exists
  tags: packages

- name: Install Packages on Windows
  win_chocolatey:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "brave" ]
    state: latest
  when: ansible_system == "Windows"
  tags: packages
