# - name: shutter ppa (ppa:linuxuprising/shutter)
#   # become: true
#   apt_repository:
#    repo: ppa:linuxuprising/shutter
#    state: present
#    update_cache: False

# - name: Update packages
#   apt:
#     upgrade: 'yes'

- name: Install packages
  become: true
  apt:
    name: [ "curl", "stow", "vim", "git", "ufw", "tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "unzip", "build-essential" ]
    state: latest

# Provide install instructions for alacritty
