- name: Pull SQL Server container
  ansible.builtin.command: podman pull mcr.microsoft.com/mssql/server:2019-latest
  tags: sqlserver

- name: Create SQL Server data directory
  become: true
  ansible.builtin.file:
    path: /var/mssql/data
    state: directory
    mode: "0755"
  tags: sqlserver

- name: Create SQL Server pod
  ansible.builtin.command: >
    podman run -d
    -e 'ACCEPT_EULA=Y'
    -e 'MSSQL_SA_PASSWORD={{ sql_server_password }}'
    --name {{ sql_server_pod_name }}
    -p 1460:1433
    -v /var/mssql/data:/var/mssql/data:Z
    mcr.microsoft.com/mssql/server:2019-latest
  tags: sqlserver
