- name: Ensure .ssh directory exists
  ansible.builtin.file:
    dest: "{{ home_dir }}/.ssh"
    mode: "0700"
    owner: "{{ user }}"
    state: directory
  tags: ssh

- name: Install ssh private key
  ansible.builtin.copy:
    src: "./.ssh/github_rsa"
    dest: "{{ home_dir }}/.ssh/github_rsa"
    owner: "{{ user }}"
    mode: "0600"
  tags: ssh

- name: Install ssh public key
  ansible.builtin.copy:
    src: "./.ssh/github_rsa.pub"
    dest: "{{ home_dir }}/.ssh/github_rsa.pub"
    owner: "{{ user }}"
    mode: "0644"
  tags: ssh

- name: Set authorized key from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', home_dir + '/.ssh/github_rsa.pub') }}"
  tags: ssh

- name: Enable SSH through UFW
  become: true
  community.general.ufw:
    rule: allow
    name: OpenSSH
  tags: ssh
