- name: Ensure .ssh directory exists.
  become_user: "{{ lookup('env', 'USER') }}"
  file:
    dest: "{{ home_dir }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh

- name: Install ssh key
  become_user: "{{ user }}"
  copy:
    src: "./.ssh/github_rsa"
    dest: "{{ home_dir }}/.ssh/github_rsa"
    mode: 0600
  tags:
    - dotfiles
    - ssh

- name: Set authorized key from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/github_rsa.pub') }}"
  tags:
    - dotfiles
    - ssh

# - name: Ensure SSH directory exists
#   file:
#     path: "{{ home_dir }}/.ssh"
#     state: directory
#     mode: '0700'

# - name: Install Encrypted SSH Private Key
#   debug:
#     msg: "Installing encrypted SSH private key."
#   when: ssh_private_key is defined

# - name: Copy SSH Private Key
#   copy:
#     content: "{{ ssh_private_key }}"
#     dest: "{{ home_dir }}/.ssh/github_rsa"
#     mode: '0600'
#   when: ssh_private_key is defined

# - name: Print Public Key Path
#   debug:
#     msg: "Public Key Path: {{ home_dir }}/.ssh/github_rsa.pub"
#   when: ssh_private_key is defined

# - name: Install Public Key
#   authorized_key:
#     user: "{{ user }}"
#     key: "{{ lookup('file', home_dir + '/.ssh/github_rsa.pub') }}"
#   when: ssh_private_key is defined

# - name: Ensure .ssh directory exists.
#   become_user: root
#   file:
#     dest: "{{ dest_key | dirname }}"
#     mode: 0700
#     state: directory
#   tags:
#     - dotfiles
#     - ssh

# - name: List .ssh folder
#   command: ls .ssh -a
#   register: ls_output

# - name: Print LS Output
#   debug:
#     msg: "{{ ls_output.stdout_lines }}"

# - name: Install ssh key
#   become_user: root
#   copy:
#     src: "{{ source_key }}"
#     dest: "{{ dest_key }}"
#     mode: 0600
#   tags:
#     - dotfiles
#     - ssh

# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ user }}"
#     # state: present
#     key: "{{ lookup('file', home_dir + '/.ssh/github_rsa.pub') }}"
#   tags:
#     - dotfiles
#     - ssh
