- name: Ensure .ssh directory exists
  become: root
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: Install ssh key
  become: root
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600

- name: Install ssh key public
  become: root
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644

- name: Set authorized keys from files
  become: root
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/github_rsa.pub"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
