- name: Ensure .ssh directory exists.
  file:
    dest: "{{ home_dir }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh

- name: Install ssh key
  copy:
    src: "./.ssh/github_rsa"
    dest: "{{ home_dir }}/.ssh/github_rsa"
    mode: 0600
  tags:
    - dotfiles
    - ssh

- name: Install ssh key public
  become_user: "{{ user }}"
  copy:
    src: "./.ssh/github_rsa.pub"
    dest: "{{ home_dir }}/.ssh/github_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', home_dir + '/.ssh/github_rsa.pub') }}"
  with_fileglob:
    - "{{ home_dir }}/.ssh/*.pub"
  tags:
    - dotfiles
    - ssh

- name: eval ssh agent
  shell: eval "$(ssh-agent -s)"

- name: add ssh key
  shell: ssh-add ~/.ssh/github_rsa
