- name: Install tpm
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ home_dir }}/.tmux/plugins/tpm"
    version: master

- name: Source tmux
  shell: "tmux source {{ home_dir }}/.tmux.conf"
