- name: Check if yazi is installed
  ansible.builtin.shell: command -v yazi
  register: yazi_exists
  changed_when: false
  failed_when: false
  tags: yazi

- name: Install yazi
  ansible.builtin.command: "{{ home_dir }}/.cargo/bin/cargo install --locked yazi-fm yazi-cli"
  when: yazi_exists.rc != 0
  tags: yazi
